# Generated by Django 3.0 on 2020-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoshnik_api', '0002_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='color',
            field=models.CharField(choices=[('Wh', 'White'), ('Rd', 'Red'), ('Yw', 'Yellow'), ('Gn', 'Green'), ('Bl', 'Blue'), ('Cn', 'Cyan')], default='Wh', max_length=2),
        ),
    ]
